name: publish
on:
  push:
    branches:
      - publishing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'
      - uses: bahmutov/npm-install@v1
      # Seems like after squash & merge the author is unknown to lerna
      - run: git config --global user.email "jan@amann.me" && git config --global user.name "Jan Amann"
      - run: lerna version prerelease --no-git-tag-version --yes
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - run: cd packages/next-intl && npm publish --tag prerelease
#        env:
#          NPM_AUTH: ${{ secrets.NPM_AUTH }}
#      - run: npm_config__auth=$NPM_AUTH yarn run publish --yes --legacy-auth $NPM_AUTH
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_AUTH: ${{ secrets.NPM_AUTH }}
